### ISSUE TITLE
Global configuration is ignored

### ISSUE THREAD

**Issue by kassovix** [goober/sonarqube-pullrequest-decorator-plugin#5]
SonarQube version 7.9.2

Sonar properties contains:
`sonar.pullrequest.bitbucket.endpoint=https://subdomain.domain.name`
In Global > Configuration > Pull reuqest, the properties is overloaded with:
`sonar.pullrequest.bitbucket.endpoint=https://anothersubdomain.domain.name`

When running pull-requests analysis, it's `subdomain` is used instead of `anotherdomain`.
My use case is to validate Sonar on a staging environment with a diffrent Bitbucket URL.

**Comment by kassovix** [comment]
It seems we should pick the value from `scannerContext` and the from properties configuration as a fallback.
See https://github.com/mc1arke/sonarqube-community-branch-plugin/blob/e129d90ec29e6b38630a39d7ebb0dd2606db8873/src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/UnifyConfiguration.java#L37

**Comment by kassovix** [comment]
I found some official documentation here: https://docs.sonarqube.org/latest/extend/developing-plugin/ (section _Configuration_)

**Comment by goober** [comment]
This project has been merged into https://github.com/mc1arke/sonarqube-community-branch-plugin please open any issues there
