### ISSUE TITLE
Azure Devops not available as Pull requester provider

### ISSUE THREAD

**Issue by Malone5923** [goober/sonarqube-pullrequest-decorator-plugin#8]
I have SonarQube 8 installed and branch community plugin installed. I cant find azure devops in the list of pull request providers on SonarQube Configuration Dashboard. I can successfully run PR but can see it decorate vulnerabilities. Please assist.

**Comment by goober** [comment]
This project har been merged into https://github.com/mc1arke/sonarqube-community-branch-plugin please open any issues there.
