### ISSUE TITLE
Archive project

### ISSUE THREAD

**Issue by gbonnefille** [goober/sonarqube-pullrequest-decorator-plugin#9]
Hi,
It seems that https://github.com/mc1arke/sonarqube-community-branch-plugin now support pull request decoration. Perhaps can you archive this project, referencing the sonarqube-community-branch-plugin.

(Would help to focus on a single project for contributions)

**Comment by goober** [comment]
Yes, thank you for the reminder. The functionality of this project has been merged with the original plugin as you state.
